/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgershopoop.view;

import burgershopoop.controller.CustomerFormController;
import burgershopoop.model.Customer;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author sayum
 */
public class ManageCustomersForm extends javax.swing.JFrame {
    
    
    private CustomerFormController customerFormController;
    
    public ManageCustomersForm() {
    initComponents();
}

    /**
     * Creates new form ManageCustomersForm
     */
    public ManageCustomersForm(CustomerFormController controller){
         initComponents();
         this.customerFormController = controller;
       
    }
    
    private void clearFields() {
        txtCustomerId.setText("");
        txtCustomerName.setText("");
        txtCustomerAddress.setText("");
        txtCustomerContactNo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCustomerContactNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddCustomerOnAction = new javax.swing.JButton();
        btnUpdateCustomerOnAction = new javax.swing.JButton();
        btnDeleteCustomerOnAction = new javax.swing.JButton();
        btnBackOnAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Customers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Add Customer");

        jLabel3.setText("Customer ID:");

        jLabel4.setText("Name:");

        jLabel5.setText("Address:");

        jLabel6.setText("Contact No:");

        jLabel7.setText("Name:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Address", "Contact No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAddCustomerOnAction.setBackground(new java.awt.Color(0, 204, 0));
        btnAddCustomerOnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCustomerOnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCustomerOnAction.setText("Add");
        btnAddCustomerOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerOnActionActionPerformed(evt);
            }
        });

        btnUpdateCustomerOnAction.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdateCustomerOnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateCustomerOnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCustomerOnAction.setText("Update");
        btnUpdateCustomerOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerOnActionActionPerformed(evt);
            }
        });

        btnDeleteCustomerOnAction.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteCustomerOnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCustomerOnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCustomerOnAction.setText("Delete");
        btnDeleteCustomerOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerOnActionActionPerformed(evt);
            }
        });

        btnBackOnAction.setBackground(new java.awt.Color(0, 0, 0));
        btnBackOnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackOnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnBackOnAction.setText("Back");
        btnBackOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackOnActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBackOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCustomerContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnAddCustomerOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdateCustomerOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeleteCustomerOnAction, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteCustomerOnAction, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnUpdateCustomerOnAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCustomerOnAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(btnBackOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnAddCustomerOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerOnActionActionPerformed
      String id = txtCustomerId.getText();
      String name = txtCustomerName.getText();
      String address = txtCustomerAddress.getText();
      String contactNo = txtCustomerContactNo.getText();
      
     Customer customer = new Customer(id, name, address, contactNo);
     
     //CustomerFormController customerFormController =new CustomerFormController();
     boolean isAddCustomer = customerFormController.addCustomer(customer);
     
     
      if (isAddCustomer) {
            JOptionPane.showMessageDialog(
                this,
                "Customer added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            
             model.insertRow(0,new Object[]{id, name, address, contactNo});    
             
        clearFields();
    
        
       
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Failed to add customer.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    
       
     
     
    }//GEN-LAST:event_btnAddCustomerOnActionActionPerformed

    private void btnUpdateCustomerOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerOnActionActionPerformed
      String id = txtCustomerId.getText();
      String name = txtCustomerName.getText();
      String address = txtCustomerAddress.getText();
      String contactNo = txtCustomerContactNo.getText();
      
     Customer customer = new Customer(id, name, address, contactNo);
     
     //CustomerFormController customerFormController =new CustomerFormController();
     boolean isUpdated = customerFormController.updateCustomer(customer);
     
     
      if (isUpdated) {
            JOptionPane.showMessageDialog(
                this,
                "Customer Updated successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            
            int selectedRow = jTable1.getSelectedRow();
            if(selectedRow != -1){
                model.setValueAt(id,selectedRow,0);
                model.setValueAt(name,selectedRow,1);
                model.setValueAt(address,selectedRow,2);
                model.setValueAt(contactNo,selectedRow,3);
                
                
            }
     
          clearFields();
      }else{
              JOptionPane.showMessageDialog(
                this,
                "Failed to update customer. Make sure the ID exists.",
                "Error",
                JOptionPane.ERROR_MESSAGE   
              );
              }
            
            
            
    }//GEN-LAST:event_btnUpdateCustomerOnActionActionPerformed

    private void btnDeleteCustomerOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerOnActionActionPerformed
      String id = txtCustomerId.getText();
      String name = txtCustomerName.getText();
      String address = txtCustomerAddress.getText();
      String contactNo = txtCustomerContactNo.getText();
      
     Customer customer = new Customer(id, name, address, contactNo);
     
   //  CustomerFormController customerFormController =new CustomerFormController();
     boolean isDeleted = customerFormController.deleteCustomer(customer);
     
     
      if (isDeleted) {
            JOptionPane.showMessageDialog(
                this,
                "Customer deleted successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            
             int selectedRow = jTable1.getSelectedRow();
            if(selectedRow != -1){
                model.removeRow(selectedRow);
            }
            
             //model.insertRow(0,new Object[]{id, name, address, contactNo});  
     
          clearFields();
      }else{
              JOptionPane.showMessageDialog(
                this,
                "Failed to delete customer. Make sure the ID exists.",
                "Error",
                JOptionPane.ERROR_MESSAGE   
              );
              }
            
            
    }//GEN-LAST:event_btnDeleteCustomerOnActionActionPerformed

    private void btnBackOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackOnActionActionPerformed
             MainDashBoardForm dashboard = new MainDashBoardForm();
             
             dashboard.setVisible(true);
             
             this.dispose();
    }//GEN-LAST:event_btnBackOnActionActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       //  ArrayList<Customer> customerList = new ArrayList<>();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomerOnAction;
    private javax.swing.JButton btnBackOnAction;
    private javax.swing.JButton btnDeleteCustomerOnAction;
    private javax.swing.JButton btnUpdateCustomerOnAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContactNo;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
